#! /bin/bash
rm dynamo_api.zip
# add packages
pip install --target ./package -r requirements.txt
pip install --target ./package .

# add files to package
cd package
cp ../lambda_function.py .
zip -r9 ../dynamo_api.zip .
cd ../
# cleanup intermediate
rm -Rvf package
